spring:
  application:
    name: example

app:
   message: Hello from application properties
   listing:
      value: 1,2,3
      
my.message: Hi from application properties

db:
   connection: "{connectionString: 'http://....', userName= 'foo', password= '123'}"
   host: 127.0.0.1
   port: 1200
   
management:  endpoints:    web:      exposure:        exclude: "*"
   
spring.cloud.config.uri: http://localhost:8888   